name: Publish Development
on:
  push:
    tags:
      - 'v0.0.*'

jobs:
  publish:
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/v') && endsWith(github.event.base_ref, '/dev')
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: "Release PR info"
        if: github.event_name != 'workflow_dispatch'
        run: echo "PR ${{ github.event.number }}"
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '16'
          registry-url: 'https://npm.pkg.github.com'
          scope: '@onqlavelabs'
          always-auth: 'true'
      - run: npm ci
      - name: Build Library
        run: npm run build
        continue-on-error: true
      - name: Extract tag version
        id: extract_tag
        run: echo "::set-output name=tag::$(echo ${{ github.ref }} | sed -e 's/^refs\/tags\/v//' -e 's/^refs\/heads\/v//')"
      - name: Update package.json version
        run: |
          sed -i "s/\"version\": \".*\"/\"version\": \"${{ steps.extract_tag.outputs.tag }}\"/" package.json
      - name: Publish the release to NPM
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}