name: Publish Development
on:
  pull_request:
    types:
      - closed
    branches:
      - dev
    paths:
      - 'package.json'
  workflow_dispatch:

jobs:
  publish:
    if: github.event_name == 'workflow_dispatch' || github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: "Release PR info"
        if: github.event_name != 'workflow_dispatch'
        run: echo "PR ${{ github.event.number }}"
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          registry-url: 'https://npm.pkg.github.com'
          scope: '@onqlave'
      - run: npm ci
      - name: get-npm-version
        id: package-version
        uses: martinbeentjes/npm-get-version-action@main
      - name: Check version convention
        run: |
          version="${{ steps.package-version.outputs.current-version }}"
          if [[ ! "$version" =~ ^0\.0\.[0-9]{1,3}$ ]]; then
            echo "Invalid version convention. Expected v0.0.x with x in the range 0-999."
            exit 1
          fi
      ############# TAG RELEASE ##############
      - name: "Push tag v${{ steps.package-version.outputs.current-version }}"
        uses: rickstaa/action-create-tag@v1
        id: tag_version
        with:
          tag: "v${{ steps.package-version.outputs.current-version }}"
          force_push_tag: true
      ############# NPM RELEASE ##############
      - name: Publish the release to NPM
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}